### ISSUE TITLE
Not working on portainer on linux

### ISSUE THREAD

**Issue by hetlelid** [Ramo-Y/BulkRename#18]
Tried to run by using portainer with docker-compose.

Chome responce:
> This page isn’t working
> 192.168.1.164 didn’t send any data.
> ERR_EMPTY_RESPONSE

Container is running, i can log in to the shell, and list the Files folder.
The container logs shows:
`[22:21:12 WRN] Overriding HTTP_PORTS '8080' and HTTPS_PORTS ''. Binding to values defined by URLS instead 'http://*:8080'.
[22:21:12 INF] Now listening on: http://[::]:8080
`

**Comment by Ramo-Y** [comment]
Hi @hetlelid,

Did you add the environment variable `ASPNETCORE_URLS` with the value `http://*:8080` like [here](https://github.com/Ramo-Y/BulkRename/blob/8d4e50b64436803e34afa87a1f16f81d85c572c3/src/docker-compose.yml#L20C7-L20C22)?
If not, please add it and try again, and let me know if it still doesn`t work.

**Comment by hetlelid** [comment]
I found the problem. The ports specifications in the README.md is wrong. It was 8080:80, but should be 8080:8080. Working now. Thanks. Sent a pull request to update the file.

**Comment by Ramo-Y** [comment]
You are right, I had it correctly in `docker-compose.yml`, but not in the readme. Many thanks for the fix!

@all-contributors
please add @hetlelid for doc
